name: Feature request
description: Suggest an idea for this project
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: |
        List the conditions that must be met in order to close this issue.
      placeholder: |
        - Users can do ◯◯
        - The API response includes △△
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: Background
      description: |
        Describe the context for this issue and the problem you want to solve.
        Why is this needed now? What is painful in the current situation?
    validations:
      required: true

  - type: textarea
    id: out_of_scope
    attributes:
      label: Out of scope (won't do in this issue)
      description: |
        Describe what is explicitly out of scope for this issue.
        Include items that might be done in the future but will not be handled in this issue.
    validations:
      required: false

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      value: |
        - [ ] Task 1
        - [ ] Task 2
    validations:
      required: false
